# Generated by Django 5.1.7 on 2025-03-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile_contact_number_profile_entry_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='type',
            field=models.CharField(choices=[('regularclasses', 'Regular Classes'), ('doubts', 'Doubts'), ('exams', 'Exams')], default='regularclasses', max_length=20),
        ),
    ]
