# Generated by Django 5.1.7 on 2025-03-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_gallery_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='year',
            field=models.IntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='gallery/'),
        ),
    ]
