# Generated by Django 5.1.7 on 2025-03-18 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='contact_number',
            new_name='mobile_number',
        ),
        migrations.AddField(
            model_name='profile',
            name='webmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(
                choices=[
                    ('Coordinator', 'Coordinator'),
                    ('Slot Coordinator', 'Slot Coordinator'),
                    ('Student', 'Student'),
                    ('Admin', 'Admin'),
                ],
                default='Slot Coordinator',
                max_length=20
            ),
        ),
    ] 